# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2025-12-15 17:56:52
"""
import arcpy

def Model():  # Model

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    arcpy.ImportToolbox(r"c:\program files\arcgis\pro\Resources\ArcToolbox\toolboxes\Conversion Tools.tbx")
    service_keck_Sheet1_csv = "C:\\Users\\pnavi\\Downloads\\service_keck - Sheet1.csv"
    ArcGIS_World_Geocoding_Service = "https://geocode.arcgis.com/arcgis/rest/services/World/GeocodeServer/ArcGIS World Geocoding Service"
    service_keck_Sheet1_csv_2_ = "C:\\Users\\pnavi\\Downloads\\service_keck - Sheet1.csv"
    MLKCH_Service_Sheet1_csv = "C:\\Users\\pnavi\\Downloads\\MLKCH_Service - Sheet1.csv"
    ladowntownmc_Service_Sheet1_csv = "C:\\Users\\pnavi\\Downloads\\ladowntownmc_Service - Sheet1.csv"
    sch_hollywood_Service_Sheet1_csv = "C:\\Users\\pnavi\\Downloads\\sch-hollywood_Service - Sheet1.csv"
    lach_la_Service_Sheet1_csv = "C:\\Users\\pnavi\\Downloads\\lach-la_Service - Sheet1.csv"
    dignity_Service_Sheet1_csv = "C:\\Users\\pnavi\\Downloads\\dignity_Service - Sheet1.csv"
    lach_la_Service_Sheet1_csv_2_ = "C:\\Users\\pnavi\\Downloads\\lach-la_Service - Sheet1.csv"
    ucla_Service_Sheet1_csv = "C:\\Users\\pnavi\\Downloads\\ucla_Service - Sheet1.csv"
    Code_Folder_2_ = "C:\\Users\\pnavi\\OneDrive\\Documents\\Code Folder"

    # Process: Geocode Addresses (5) (GeocodeAddresses) (geocoding)
    Keck_Hospital = "C:\\Users\\pnavi\\OneDrive\\Documents\\ArcGIS\\Projects\\MyProject14\\MyProject14.gdb\\Keck_Hospital"
    arcpy.geocoding.GeocodeAddresses(in_table=service_keck_Sheet1_csv, address_locator=ArcGIS_World_Geocoding_Service, in_address_fields="'Single Line Input' Address VISIBLE NONE", out_feature_class=Keck_Hospital, country=["USA"])

    # Process: Geocode Addresses (GeocodeAddresses) (geocoding)
    USC_Norris_Hospital = "C:\\Users\\pnavi\\OneDrive\\Documents\\ArcGIS\\Projects\\MyProject14\\MyProject14.gdb\\USC_Norris_Hospital"
    arcpy.geocoding.GeocodeAddresses(in_table=service_keck_Sheet1_csv_2_, address_locator=ArcGIS_World_Geocoding_Service, in_address_fields="'Single Line Input' Address1 VISIBLE NONE", out_feature_class=USC_Norris_Hospital, country=["USA"])

    # Process: Geocode Addresses (6) (GeocodeAddresses) (geocoding)
    MLKCH = "C:\\Users\\pnavi\\OneDrive\\Documents\\ArcGIS\\Projects\\MyProject14\\MyProject14.gdb\\MLKCH"
    arcpy.geocoding.GeocodeAddresses(in_table=MLKCH_Service_Sheet1_csv, address_locator=ArcGIS_World_Geocoding_Service, in_address_fields="'Single Line Input' Address VISIBLE NONE", out_feature_class=MLKCH, country=["USA"])

    # Process: Geocode Addresses (2) (GeocodeAddresses) (geocoding)
    ladowntownmc = "C:\\Users\\pnavi\\OneDrive\\Documents\\ArcGIS\\Projects\\MyProject14\\MyProject14.gdb\\ladowntownmc"
    arcpy.geocoding.GeocodeAddresses(in_table=ladowntownmc_Service_Sheet1_csv, address_locator=ArcGIS_World_Geocoding_Service, in_address_fields="'Single Line Input' Address VISIBLE NONE", out_feature_class=ladowntownmc, country=["USA"])

    # Process: Geocode Addresses (4) (GeocodeAddresses) (geocoding)
    schhollywood = "C:\\Users\\pnavi\\OneDrive\\Documents\\ArcGIS\\Projects\\MyProject14\\MyProject14.gdb\\schhollywood"
    arcpy.geocoding.GeocodeAddresses(in_table=sch_hollywood_Service_Sheet1_csv, address_locator=ArcGIS_World_Geocoding_Service, in_address_fields="'Single Line Input' Address VISIBLE NONE", out_feature_class=schhollywood, country=["USA"])

    # Process: Geocode Addresses (3) (GeocodeAddresses) (geocoding)
    ucla_Service = "C:\\Users\\pnavi\\OneDrive\\Documents\\ArcGIS\\Projects\\MyProject14\\MyProject14.gdb\\ucla_Service"
    arcpy.geocoding.GeocodeAddresses(in_table=lach_la_Service_Sheet1_csv, address_locator=ArcGIS_World_Geocoding_Service, in_address_fields="'Single Line Input' Address VISIBLE NONE", out_feature_class=ucla_Service, country=["USA"])

    # Process: Geocode Addresses (7) (GeocodeAddresses) (geocoding)
    dignity_Service = "C:\\Users\\pnavi\\OneDrive\\Documents\\ArcGIS\\Projects\\MyProject14\\MyProject14.gdb\\dignity_Service"
    arcpy.geocoding.GeocodeAddresses(in_table=dignity_Service_Sheet1_csv, address_locator=ArcGIS_World_Geocoding_Service, in_address_fields="'Single Line Input' Address VISIBLE NONE", out_feature_class=dignity_Service, country=["USA"])

    # Process: Geocode Addresses (8) (GeocodeAddresses) (geocoding)
    lachla_Service_GeocodeAddres = "C:\\Users\\pnavi\\OneDrive\\Documents\\ArcGIS\\Projects\\MyProject14\\MyProject14.gdb\\lachla_Service_GeocodeAddres"
    arcpy.geocoding.GeocodeAddresses(in_table=lach_la_Service_Sheet1_csv_2_, address_locator=ArcGIS_World_Geocoding_Service, in_address_fields="'Single Line Input' Address VISIBLE NONE", out_feature_class=lachla_Service_GeocodeAddres, country=["USA"])

    # Process: Geocode Addresses (9) (GeocodeAddresses) (geocoding)
    ucla_service_2_ = "C:\\Users\\pnavi\\OneDrive\\Documents\\ArcGIS\\Projects\\MyProject14\\MyProject14.gdb\\ucla_service"
    arcpy.geocoding.GeocodeAddresses(in_table=ucla_Service_Sheet1_csv, address_locator=ArcGIS_World_Geocoding_Service, in_address_fields="'Single Line Input' Address VISIBLE NONE", out_feature_class=ucla_service_2_, country=["USA"])

    # Process: Feature Class To Shapefile (FeatureClassToShapefile) (conversion)
    Code_Folder = arcpy.conversion.FeatureClassToShapefile(Input_Features=[Keck_Hospital, USC_Norris_Hospital, MLKCH, ladowntownmc, schhollywood, ucla_Service, dignity_Service, lachla_Service_GeocodeAddres, ucla_service_2_], Output_Folder=Code_Folder_2_)[0]

if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace="C:\\Users\\pnavi\\OneDrive\\Documents\\ArcGIS\\Projects\\MyProject14\\MyProject14.gdb", workspace="C:\\Users\\pnavi\\OneDrive\\Documents\\ArcGIS\\Projects\\MyProject14\\MyProject14.gdb"):
        Model()
